name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    uses: ComputerComa/Facotorio-rcon-gui/blob/24c6de52e9eb3ff32b2c4832c32d184a938756f7/.github/workflows/python-app.yml@main
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs: build

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.exe
