name: "tagged-release"

on:
  push:
    tags:
      - "v*"
      - "V*"

jobs:
  build:
    uses: ComputerComa/Facotorio-rcon-gui/.github/workflows/python-app.yml@main
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    needs: build

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: main
      - name: Display structure of downloaded files
        run: ls -R
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            *.exe
